spring:
  application:
    name: bookstore-backend
  profiles:
    active: h2
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  error:
    include-message: always

# JWT Configuration
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000 # 24 Hours

# Actuator & Prometheus Metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# Swagger OpenAPI Docs
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
