spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-db:3306/bookstoredb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:mysql}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis-cache}
      port: ${SPRING_REDIS_PORT:6379}
