spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/bookstoredb}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis-cache}
      port: ${SPRING_REDIS_PORT:6379}
